language: ruby
git:
  depth: false
cache: bundler
before_install:
- bundle install
after_success:
- script/tag_on_master
script: bundle exec rake book:build
before_deploy: bundle install && bundle exec rake book:build
deploy:
  provider: releases
  file:
  - progit.epub
  - progit.mobi
  - progit.pdf
  skip_cleanup: true
  on:
    tags: true
branches:
  only:
  - master
  - /^2\.1(\.\d+)+$/

notifications:
  email:
    on_success: never
    on_failure: always
